apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ default "" .Values.namespace }}
  name: {{ include "frontier-squid.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "frontier-squid.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "frontier-squid.chart" . }}
spec:
  replicas: {{ default 1 .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "frontier-squid.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "frontier-squid.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.image.pullPolicy }}
        ports:
          - containerPort: 3128
            protocol: TCP
#        livenessProbe:
#          exec:
#            command:
#              - /usr/sbin/frontier-squid.
#              - -k 
#              - parse
#          initialDelaySeconds: 5
#          periodSeconds: 5
#        readinessProbe:
#          exec:
#            command:
#              - /usr/sbin/frontier-squid.
#              - -k 
#              - parse
#          initialDelaySeconds: 5
#          periodSeconds: 5
        volumeMounts:
          - name: frontier-squid-config
            mountPath: /etc/squid/squid.conf
            subPath: squid.conf
      volumes:
        - name: frontier-squid-config
          configMap:
            name: {{ include "frontier-squid.fullname" . }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
#    {{- with .Values.affinity }}
#      affinity:
#        {{- toYaml . | nindent 8 }}
#    {{- end }}
#    {{- with .Values.tolerations }}
#      tolerations:
#        {{- toYaml . | nindent 8 }}
#    {{- end }}
