apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frontier-squid.fullname" . }}
  labels:
    {{- include "frontier-squid.labels" . | nindent 4 }}
spec:
  replicas: {{ default 1 .Values.replicas }}
  selector:
   matchLabels:
     {{- include "frontier-squid.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "frontier-squid.selectorLabels" . | nindent 8 }}
        {{- toYaml .Values.customLabels | nindent 8 }}
    spec:
      {{- if .Values.podAssignment.enableNodeSelector }}
      nodeSelector:
        {{- toYaml .Values.customLabels | nindent 8 }}
      {{- end }}
      {{- if .Values.podAssignment.enablePodAntiAffinity }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                {{- range $key, $val := .Values.customLabels }}
                - key: {{ $key }}
                  operator: In
                  values:
                  - {{ $val }}
                {{- end }}
              topologyKey: "kubernetes.io/hostname"
      {{- end }}
      initContainers:
        - name: frontier-squid-init0-makedirs
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ default "IfNotPresent" .Values.image.pullPolicy }}
          command: ["/usr/sbin/squid", "-f", "/etc/squid/squid.conf", "-N", "-z"]
          volumeMounts:
            - name: frontier-squid-config
              mountPath: /etc/squid/squid.conf
              subPath: squid.conf
            - name: frontier-squid-disk-cache
              mountPath: {{ default "/var/cache/squid" .Values.config.cache.diskDirectory }}
      containers:
      - name: frontier-squid
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.image.pullPolicy }}
        command: ["/usr/sbin/squid", "-f", "/etc/squid/squid.conf", "-N", "-d1"]
#        livenessProbe:
#          exec:
#            command:
#              - /usr/sbin/frontier-squid.
#              - -k 
#              - parse
#          initialDelaySeconds: 5
#          periodSeconds: 5
#        readinessProbe:
#          exec:
#            command:
#              - /usr/sbin/frontier-squid.
#              - -k 
#              - parse
#          initialDelaySeconds: 5
#          periodSeconds: 5
        volumeMounts:
          - name: frontier-squid-config
            mountPath: /etc/squid/squid.conf
            subPath: squid.conf
          - name: frontier-squid-disk-cache
            mountPath: {{ default "/var/cache/squid" .Values.config.cache.diskDirectory }}
      volumes:
        - name: frontier-squid-config
          configMap:
            name: {{ include "frontier-squid.fullname" . }}-config
        - name: frontier-squid-disk-cache
          emptyDir: {}
