apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontier-squid.fullname" . }}
  labels:
    {{- include "frontier-squid.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3128
      targetPort: 3128
      protocol: TCP
      name: squid
  selector:
    {{- include "frontier-squid.selectorLabels" . | nindent 4 }}

