apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontier-squid.fullname" . }}
  labels:
    {{- include "frontier-squid.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.service.ports }}
  - name: {{ .name }}
    protocol: TCP
    port: {{ .port }}
    targetPort: {{ .targetPort }}
  {{- end }}
  selector:
    {{- include "frontier-squid.selectorLabels" . | nindent 4 }}

