[shared]
gatewaysvc = "localhost:9142"
jwt_secret = "POZSOrlP7AgnTxH7MJebWV8ohvsApgbd4u3Joen30c"

[grpc]
address = "0.0.0.0:16000"

[grpc.services.storageprovider]
driver = "eos"
mount_path = "/eos/user"
mount_id = "eos"
data_server_url = "http://localhost:15000/data"

[grpc.services.storageprovider.drivers.eos]
namespace = "/eos/user/"
quota_node = "/eos/user/"
master_url = "root://eos-mgm.default.svc.cluster.local:1094"
slave_url = "root://eos-mgm.default.svc.cluster.local:1094"
user_layout = "{{substr 0 1 .Username}}/{{.Username}}"
xrdcopy_binary = "/opt/eos/xrootd/bin/xrdcopy"
cache_directory = "/tmp/reva"

[http]
address = "0.0.0.0:15000"

[http.services.dataprovider]
driver = "eos"

[http.services.dataprovider.drivers.eos]
namespace = "/eos/user/"
quota_node = "/eos/user/"
master_url = "root://eos-mgm.default.svc.cluster.local:1094"
slave_url = "root://eos-mgm.default.svc.cluster.local:1094"
user_layout = "{{substr 0 1 .Username}}/{{.Username}}"
xrdcopy_binary = "/opt/eos/xrootd/bin/xrdcopy"
cache_directory = "/tmp/reva"