image:
  repository: gitlab-registry.cern.ch/dss/eos
  tag: 4.8.39
  pullPolicy: Always

eosMgmUrl: eos-mgm-0.eos-mgm.default.svc.cluster.local

config:
  spaceDefault:
    groupSize: 8
    groupMod: 1

  sys:
    recycle: "/eos/user/proc/recycle/"
    versioning: 10

  sysForced:
    blockchecksum: crc32c
    blocksize: 4k
    checksum: adler
    layout: replica
    nstripes: 2
    space: default
    maxsize: "10000000000"

  recycle:
    enable: true
    params:
      size: 10G
      inodes: 10M
      lifetime: "2592000" # 30 days in seconds
      ratio: 0.2

  directoryTree:
    create: true
    prefix: "/eos/user"

  demoUsers:
    createUsers: true
    createHomeDirs: true
    users:
      unamePrefix: "user"
      uidStart: 1000
      gname: "users"
      gid: 100
      howMany: 10
    quota:
      size: 1T
      inodes: 1M

customLabels:
  service: eos
  component: eos-mgm

podAssignment:
  enableNodeSelector: false     # Requires a node labeled as per customLabels
