image:
  repository: gitlab-registry.cern.ch/dss/eos/eos-all
  tag: 4.8.57
  pullPolicy: Always

#
# SSS keytab to authenticate against eos mgm
#   The name of the kubernetes secret containing the eos keytab to use.
# Default: eos-sss-keytab
sssKeytab:
  secret:

config:
  spaceDefault:
    groupSize: 8
    groupMod: 1

  sys:
    recycle: "/eos/user/proc/recycle/"
    versioning: 10

  sysForced:
    blockchecksum: crc32c
    blocksize: 4k
    checksum: adler
    layout: replica
    nstripes: 2
    space: default
    maxsize: "10000000000"

  recycle:
    enable: true
    params:
      size: 10G
      inodes: 10M
      lifetime: "2592000" # 30 days in seconds
      ratio: 0.2

  #
  # OAuth2
  #   Documentation at https://eos-docs.web.cern.ch/using/oauth2.html
  #
  oauth:
    enabled: true
    resourceEndpoint:
    audienceClaim:

  directoryTree:
    create: true
    prefix: "/eos/user"

  demoUsers:
    createUsers: true
    createHomeDirs: true
    users:
      unamePrefix: "user"
      uidStart: 1000
      gname: "users"
      gid: 100
      howMany: 10
    quota:
      size: 1T
      inodes: 1M

customLabels:
  service: eos
  component: eos-mgm

podAssignment:
  enableNodeSelector: false     # Requires a node labeled as per customLabels
