apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cvmfs.fullname" . }}-cfgmap-default-local
  labels:
    {{- include "cvmfs.labels" . | nindent 4 }}
data:
  default.local: |
    {{- range $key,$val := .Values.cvmfs.default_local }}
    {{ $key }}='{{ $val }}'
    {{- end }}
    CVMFS_REPOSITORIES='{{ template "repolist_csv" . }}'
