image:
  repository: osixia/openldap
  tag: 1.5.0
  pullPolicy: Always

#
# Prefer colocation with OpenLDAP pod
#   Assign weight 100 to colocation with 'component: ldap' as per custom labels.
#   The idea is to re-use the openldap container image available on the node running the actual LDAP server.
#
podAssignment:
  enableLdapColocation: true
  enableNodeSelector: false     # Requires a node labeled as per customLabels

#
# Custom labels to identify ldap-instance-config pod.
#
# They are used by node selection, if enabled (see above).
# Label nodes accordingly to avoid scheduling problems.
#
customLabels:
  service: ldap
  component: ldap


#
# The actual configuration for OpenLDAP
#
# Parameters:
#   - ldap_uri:     The URL (protocol + hostname + port) at which the LDAP server is reachable.
#                     Example: ldap://plainldapserver.example.com:389
#                              ldaps://secureldap.example.com:636
#   - ldap_binddn:  The distinguished name to bind to the LDAP server, likely with admin privileges.
#   - ldap_bindpw:  The password for the distinguished name used to bind
ldap_uri: ldap://plainldapserver.example.com:389
ldap_binddn: cn=admin,dc=example,dc=org
ldap_bindpw: admin
ldifFiles:
  readme: |-
    # This is a README file.
