replicaCount: 1

image:
  repository: gitlab-registry.cern.ch/sciencebox/docker-images/frontier-squid
  tag: 4.15-2.1
  pullPolicy: IfNotPresent

customLabels:
  service: cvmfs
  component: frontier-squid

podAssignment:
  enableNodeSelector: false     # Requires a node labeled as per customLabels.
  enablePodAntiAffinity: false  # Shard the stateful set on as many nodes as possible

enableLivenessProbe: false      # To be implemented
enableReadinessProbe: false     # To be implemented

service:
  type: ClusterIP
  ports:
  - name: squid
    port: 3128

#ingress:
#  enabled: true
#  annotations: {}
#  paths:
#    - /
#  hosts:
#    - passtlstest001.cern.ch
#  tls: []

#resources: {}
