apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ocis.fullname" . }}-config
data:
  web-config.json: |-
    {
      "server": "https://sciencebox.local",
      "theme": "owncloud",
      "version": "0.1.0",
      "openIdConnect": {
        "metadata_url": "https://sciencebox.local/.well-known/openid-configuration",
        "authority": "https://sciencebox.local",
        "client_id": "web",
        "response_type": "code",
        "scope": "openid profile email"
      },
      "apps": ["files"],
      "external_apps": [
      ],
      "options": {
        "hideSearchBar": true,
        "homeFolder": "{{ printf "/eos/user/{{substr 0 1 .Id}}/{{.Id}}" }}"
      }
    }