apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ocis.fullname" . }}-config
data:
  web-config.json: |-
    {
      "server": {{ quote .Values.config.server }},
      "version": "0.1.0",
      "openIdConnect": {
        "metadata_url": {{ quote .Values.config.metadata_url }},
        "authority": {{ quote .Values.config.authority }},
        "client_id": "web",
        "response_type": "code",
        "scope": "openid profile email"
      },
      "apps": ["files"],
      "external_apps": [
      ],
      "options": {
        "hideSearchBar": true,
        "homeFolder": "{{ printf "/eos/user/{{substr 0 1 .Id}}/{{.Id}}" }}"
      }
    }