apiVersion: v2
#
name: sciencebox
type: application
version: 0.0.1
#
description: The chart to deploy and configure ScienceBox
icon: #TODO
#
dependencies:
- name: server
  alias: eos
  version: 0.1.0
  repository: "https://registry.cern.ch/chartrepo/eos"
- name: swan
  version: 0.0.5
  repository: "https://registry.cern.ch/chartrepo/swan"
#
- name: eos-instance-config
  version: 0.0.4
  repository: "https://registry.cern.ch/chartrepo/sciencebox"
- name: ocis-idp
  version: 0.0.3
  repository: "https://registry.cern.ch/chartrepo/sciencebox"
