apiVersion: v2
#
name: sciencebox
type: application
version: 0.0.2
#
description: The chart to deploy and configure ScienceBox
icon: #TODO
#
dependencies:
- name: openldap
  alias: ldap
  version: 2.0.4
  repository: "https://jp-gouin.github.io/helm-openldap/"
- name: ldap-instance-config
  version: 0.0.1
  repository: "https://registry.cern.ch/chartrepo/sciencebox"
#
- name: server
  alias: eos
  version: 0.1.3
  repository: "https://registry.cern.ch/chartrepo/eos"
- name: eos-instance-config
  version: 0.0.5
  repository: "https://registry.cern.ch/chartrepo/sciencebox"
#
- name: swan
  version: 0.1.9
  repository: "https://registry.cern.ch/chartrepo/swan"
#
- name: ocis-idp
  version: 0.0.4
  repository: "https://registry.cern.ch/chartrepo/sciencebox"
#
- name: nginx
  version: 9.9.3
  repository: "https://charts.bitnami.com/bitnami"
